version: "3.8"

services:
  loki:
    image: grafana/loki:2.8.2
    container_name: loki
    ports:
      - "3100:3100"
    command:
      - -config.file=/etc/loki/loki-config.yaml
    volumes:
      - ./loki-config.yaml:/etc/loki/loki-config.yaml:ro
      - loki_data:/loki

  promtail:
    image: grafana/promtail:2.8.2
    container_name: promtail
    depends_on:
      - loki
    volumes:
      - ./logs:/var/log/myapp:ro
      - ./promtail-config.yaml:/etc/promtail/promtail-config.yaml:ro
      - promtail_positions:/tmp
    command:
      - -config.file=/etc/promtail/promtail-config.yaml

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    depends_on:
      - loki

  grafana:
    image: grafana/grafana-oss:9.4.7
    container_name: grafana
    depends_on:
      - loki
    ports:
      - "3000:3000"
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: "Admin"

volumes:
  loki_data:
  promtail_positions: